"""Remove confirmed field from contact_methods

Revision ID: 129f5b9efddb
Revises: 66d4823d5533
Create Date: 2022-02-14 15:32:18.607194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129f5b9efddb'
down_revision = '66d4823d5533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_methods', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_methods', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default="true"))
    # ### end Alembic commands ###
