"""Replace ContactMethodType enum for a model

Revision ID: 66d4823d5533
Revises: f27de9be890a
Create Date: 2022-02-03 19:39:38.642255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from users.core.models import ContactMethodType

# revision identifiers, used by Alembic.
revision = '66d4823d5533'
down_revision = 'f27de9be890a'
branch_labels = None
depends_on = None


def seed_contact_method_types():
    contact_method_types_list = [ContactMethodType(**kwarg) for kwarg in [
        {'description': 'EMAIL'},
        {'description': 'PHONE'},
        {'description': 'ADDRESS'},
    ]]

    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    session.add_all(contact_method_types_list)
    session.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_method_types',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description', name='u_contact_method_types_description')
    )
    op.add_column('contact_methods', sa.Column('contact_method_type_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('uix_1', 'contact_methods', type_='unique')
    op.create_unique_constraint('uix_1', 'contact_methods', ['user_id', 'contact_method_type_id', 'value'])
    op.create_foreign_key(None, 'contact_methods', 'contact_method_types', ['contact_method_type_id'], ['id'])
    op.drop_column('contact_methods', 'type')
    op.alter_column('users', 'address_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    seed_contact_method_types()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'address_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.add_column('contact_methods', sa.Column('type', postgresql.ENUM('EMAIL', 'PHONE_NUMBER', 'ADDRESS', name='contactmethodtype'), server_default=sa.text("'EMAIL'::contactmethodtype"), autoincrement=False, nullable=False))
    op.drop_constraint('uix_1', 'contact_methods', type_='unique')
    op.create_unique_constraint('uix_1', 'contact_methods', ['user_id', 'type', 'value'])
    op.drop_column('contact_methods', 'contact_method_type_id')
    op.drop_table('contact_method_types')
    # ### end Alembic commands ###
