"""user model

Revision ID: 94851c362c7a
Revises: 
Create Date: 2021-12-22 16:08:56.443004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94851c362c7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('service_agr_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_VALIDATION', 'VALIDATION_REJECTED', 'BANNED', 'BANNED_NOTIFIED', 'VALIDATED', 'ACTIVE', 'BLOCKED', name='userstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_by', sa.String(length=20), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.execute(
        'drop type userstatus'
    )
    # ### end Alembic commands ###
