"""user_address model

Revision ID: c93acbd5d2d1
Revises: c1355ca79d81
Create Date: 2022-07-28 19:58:49.919703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c93acbd5d2d1'
down_revision = 'c1355ca79d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_address',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('address_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_by', sa.String(length=20), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'address_id'),
    sa.UniqueConstraint('user_id', 'address_id', name='uc_user_addres')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_address')
    # ### end Alembic commands ###
