"""contact_method model

Revision ID: ccd4f7fb49ed
Revises: 94851c362c7a
Create Date: 2021-12-27 19:23:33.407783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccd4f7fb49ed'
down_revision = '94851c362c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_methods',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('email', sa.String(), nullable=False, default='some@email.com'),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_by', sa.String(length=20), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_methods')
    # ### end Alembic commands ###
