"""identity_validation_id on user entity

Revision ID: eb5b3bd97117
Revises: 7f05e1bb6984
Create Date: 2022-05-20 12:33:07.934675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb5b3bd97117'
down_revision = '7f05e1bb6984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identity_validation_id', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'identity_validation_id')
    # ### end Alembic commands ###
